### ISSUE TITLE
CSCore.Win32?

### ISSUE THREAD

**Issue by cdgodfrey** [KalleStae/CScore.NET6#1]
This project seems to need CSCore.Win32 to compile.  At the risk of appearing dumb: what is it and how can I get it?
Thanks

**Comment by KalleStae** [comment]
this is a copy/fork of  https://github.com/filoe/cscore changed for use with windows  .net 6.0
See the description there.

**Comment by SamDel** [comment]
Thanks for this project @KalleStae 

The CSCore/Win32 folder of the original project ([link](https://github.com/filoe/cscore/tree/master/CSCore/Win32)) is missing in your project ([link](https://github.com/KalleStae/CScore.NET6/tree/master/CScore)), that's why it doesn't compile 'out-of-the-box. I copied the folder from the original project ([https://github.com/filoe/cscore](https://github.com/filoe/cscore) into this project, then it compiled right away.

**Comment by KalleStae** [comment]
thanks for the hint. I added folder win32

**Comment by SamDel** [comment]
Great, it works fine now.
